### ISSUE TITLE
foreign interface?

### ISSUE THREAD

**Issue by wboeke** [pahihu/vfc#1]
Could you please give an example of how the foreign interface must be used?
This is what I tried:
In vfc.c:
   void test_c (int n) { printf("n = %d\n",n); }
call it in vfc:
  1 s( test_c) function:
And now ... what next?

**Comment by pahihu** [comment]
At the end of run.f there is an example:

2 function: gettimeofday
: (get-time) ( - usec sec)   0 0 sp@ 0 swap gettimeofday drop ;

LIBRARY libname
- opens the shared library, where symbols will be search, max 10 libraries

number-of-args FUNCTION: function-name
- creates the word function-name which will call function-name in a shared lib, from the stack it will pass
   number-of-args arguments to the function, it always expects that the foreign function returns a result

Regards,
pahihu

**Comment by wboeke** [comment]
I once saw this code in run.f but didn't understand it. Also I could not get a useful result when I tried it, then forgot it.
So, if you have some time to spare, please give a complete working example of a simple C function (with a parameter) in a source file, and how to call it from forth. The first parameter of dlopen() then probably must be NULL.

**Comment by pahihu** [comment]
===> cat test.c
#include <stdio.h>
void test_c(int n) { printf("n = %d\n", n); }

16:03:44 - Thu Jul 06] ~/src/github/vfc 
===> cc -shared -o libtest.dylib test.c

16:03:47 - Thu Jul 06] ~/src/github/vfc 
===> vfc run.f
library libtest.dylib

0 0 0 0 > 1 function: test_c

0 0 0 0 > 42 test_c drop
n = 42

0 0 0 0 > bye

**Comment by wboeke** [comment]
Thanks! It worked, also with string parameters.
Two small remarks: compiling must be done with -fPIC, and libtest.dylib should be ./libtest.dylib
